notify:
  test: true
plugin:
  twistlock:
    thresholdCvss: 9
    thresholdCompliance: medium
    whitelist:
      CVE-2019-9169: this is an example exception note
      CVE-2019-3861: another whitelisting test
